<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="..\..\Assets\Scripts\GShare\Runtime\**\*.cs"
             Link="GShare\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
