"""Classic CS:GO buy-menu slots; cosmetic ownership/economy is intentionally separate."""
AGENTS = [
    ('ctm_sas', 'SAS', 1), ('ctm_fbi', 'FBI', 1), ('ctm_st6_variante', '海豹六队', 1),
    ('ctm_swat_variante', 'SWAT', 1), ('ctm_gendarmerie_varianta', '法国宪兵', 1),
    ('tm_phoenix', '凤凰战士', 2), ('tm_leet_varianta', '精英分子', 2),
    ('tm_balkan_variantf', '巴尔干战士', 2), ('tm_professional_varf', '专业人士', 2),
    ('tm_jungle_raider_varianta', '丛林突袭者', 2),
]
# id, display name, category, slot, faction mask, menu animation profile
# Categories: pistols=0, rifles=1, SMGs=2, heavy=3, gear=4, snipers=5 (stable serialized IDs).
WEAPONS = [
    ('weapon_pist_hkp2000','P2000',0,'pistol.start',1,'pistol'),
    ('weapon_pist_usp_silencer','USP-S',0,'pistol.start',1,'pistol'),
    ('weapon_pist_glock18','Glock-18',0,'pistol.start',2,'pistol'),
    ('weapon_pist_elite','双持贝瑞塔',0,'pistol.dual',3,'elite'),
    ('weapon_pist_p250','P250',0,'pistol.p250',3,'pistol'),
    ('weapon_pist_fiveseven','Five-SeveN',0,'pistol.fast',1,'pistol'),
    ('weapon_pist_tec9','Tec-9',0,'pistol.fast',2,'pistol'),
    ('weapon_pist_cz75a','CZ75-Auto',0,'pistol.fast',3,'pistol'),
    ('weapon_pist_deagle','Desert Eagle',0,'pistol.heavy',3,'pistol'),
    ('weapon_pist_revolver','R8 左轮',0,'pistol.heavy',3,'revolver'),
    ('weapon_rif_famas','FAMAS',1,'rifle.budget',1,'famas'),
    ('weapon_rif_galilar','Galil AR',1,'rifle.budget',2,'galil'),
    ('weapon_rif_m4a1_silencer','M4A1-S',1,'rifle.main',1,'m4'),
    ('weapon_rif_m4a4','M4A4',1,'rifle.main',1,'m4'),
    ('weapon_rif_ak47','AK-47',1,'rifle.main',2,'ak'),
    ('weapon_rif_aug','AUG',1,'rifle.scope',1,'aug'),
    ('weapon_rif_sg556','SG 553',1,'rifle.scope',2,'ak'),
    ('weapon_snip_ssg08','SSG 08',5,'rifle.scout',3,'scout'),
    ('weapon_snip_awp','AWP',5,'rifle.awp',3,'awp'),
    ('weapon_snip_scar20','SCAR-20',5,'rifle.auto',1,'scar'),
    ('weapon_snip_g3sg1','G3SG1',5,'rifle.auto',2,'g3sg'),
    ('weapon_smg_mp9','MP9',2,'smg.light',1,'mp7'),
    ('weapon_smg_mac10','MAC-10',2,'smg.light',2,'mp7'),
    ('weapon_smg_mp7','MP7',2,'smg.silenced',3,'mp7'),
    ('weapon_smg_mp5sd','MP5-SD',2,'smg.silenced',3,'mp7'),
    ('weapon_smg_ump45','UMP-45',2,'smg.ump',3,'ump'),
    ('weapon_smg_p90','P90',2,'smg.p90',3,'p90'),
    ('weapon_smg_bizon','PP-Bizon',2,'smg.bizon',3,'bizon'),
    ('weapon_shot_nova','Nova',3,'heavy.pump',3,'nova'),
    ('weapon_shot_xm1014','XM1014',3,'heavy.auto',3,'xm'),
    ('weapon_shot_mag7','MAG-7',3,'heavy.close',1,'mag7'),
    ('weapon_shot_sawedoff','截短霰弹枪',3,'heavy.close',2,'shotgun'),
    ('weapon_mach_m249','M249',3,'heavy.m249',3,'m249'),
    ('weapon_mach_negev','Negev',3,'heavy.negev',3,'negev'),
    ('weapon_knife_default_ct','CT 战术匕首',4,'gear.knife',1,'knife'),
    ('weapon_knife_default_t','T 战术匕首',4,'gear.knife',2,'knife'),
    ('weapon_flashbang','闪光弹',4,'gear.flash',3,'grenade'),
    ('weapon_hegrenade','高爆手雷',4,'gear.he',3,'grenade'),
    ('weapon_smokegrenade','烟雾弹',4,'gear.smoke',3,'grenade'),
    ('weapon_decoy','诱饵手雷',4,'gear.decoy',3,'grenade'),
    ('weapon_incendiarygrenade','燃烧弹',4,'gear.fire',1,'grenade'),
    ('weapon_molotov','燃烧瓶',4,'gear.fire',2,'molotov'),
    ('weapon_pist_taser','Zeus x27',4,'gear.taser',3,'pistol'),
    ('w_eq_armor','防弹衣',4,'gear.armor',3,''),
    ('w_eq_armor_helmet','防弹衣 + 头盔',4,'gear.helmet',3,''),
    ('defuser','拆弹器',4,'gear.defuser',1,''),
    ('weapon_c4','C4 炸弹',4,'gear.c4',2,'c4'),
]
# A compatible menu pose for each grip family; every entry has an idle and an inspection.
PROFILES = {
    'm4': ('ct','ct_main_menu_rifle_idle_handrepo_m4','ct_main_menu_rifle_lookat_handrepo_m4'),
    'ak': ('t','t_main_menu_rifle02_idle','t_main_menu_rifle02_lookatgun'),
    'galil': ('t','t_main_menu_rifle02_idle_awp_galil','t_main_menu_rifle02_lookatgun'),
    'g3sg': ('t','t_main_menu_rifle02_idle_g3sg','t_main_menu_rifle02_lookatgun'),
    'pistol': ('ct','ct_main_menu_pistol01_idle','ct_main_menu_pistol01_lookatgun'),
    'elite': ('ct','ct_main_menu_elite_idle','ct_main_menu_elite_lookat01'),
    'revolver': ('ct','ct_main_menu_revolver_idle','ct_main_menu_revolver_lookatgun'),
    'aug': ('ct','ct_main_menu_rifle_idle_handrepo_aug','ct_main_menu_rifle_lookatwatch_handrepo_aug'),
    'famas': ('ct','ct_main_menu_famas_idle','ct_main_menu_famas_lookatwatch'),
    'scout': ('ct','ct_main_menu_rifle_ssg08_idle','ct_main_menu_rifle_ssg08_lookat'),
    'awp': ('ct','ct_main_menu_rifle_awp_idle','ct_main_menu_rifle_awp_lookat'),
    'scar': ('ct','ct_main_menu_rifle_scar_idle','ct_main_menu_rifle_scar_lookat'),
    'mp7': ('ct','ct_main_menu_mp7_idle','ct_main_menu_mp7_lookatgun'),
    'ump': ('t','t_main_menu_ump45_idle','t_main_menu_ump45_lookatgun'),
    'p90': ('ct','ct_main_menu_p90_idle','ct_main_menu_p90_lookatwatch'),
    'bizon': ('t','t_main_menu_bizon_idle','t_main_menu_bizon_lookatgun'),
    'nova': ('ct','ct_main_menu_nova_idle','ct_main_menu_nova_lookat01'),
    'xm': ('ct','ct_main_menu_xm1014_idle','ct_main_menu_xm1014_lookat01'),
    'mag7': ('ct','ct_main_menu_mag7_idle','ct_main_menu_mag7_lookatwatch'),
    'shotgun': ('t','t_main_menu_shotgun_idle','t_main_menu_shotgun_lookat01'),
    'm249': ('ct','ct_main_menu_m249_idle','ct_main_menu_m249_lookat01'),
    'negev': ('ct','ct_main_menu_negev_idle','ct_main_menu_negev_lookat01'),
    'knife': ('ct','ct_main_menu_knife_idle','ct_main_menu_knife_lookat01'),
    'grenade': ('ct','ct_main_menu_frag01_idle','ct_main_menu_frag01_lookat01'),
    'molotov': ('t','t_main_menu_molotov_idle','t_main_menu_molotov_lookat'),
    'c4': ('t','t_main_menu_c4_idle','t_main_menu_c4_lookat01'),
}
